### ISSUE TITLE
Remover efeito do hover nos cards de projetos da página principal na versão mobile

### ISSUE THREAD

**Issue by jessescn** [OpenDevUFCG/opendevufcg.org#132]
**Descreva a feature em detalhes**
Ao passar o mouse em cima dos cards, acontece um efeito onde o card afasta os outros ao seu redor, isso acontece aumentando sua _margin_. 

**Necessidade da feature:**
Como na versão mobile os cards ficam um abaixo do outro e o efeito do hover acontece ao arrastar com o dedo, o efeito não fica muito bom. 

**Como ela pode ser implementada:**
Dentro de `home/css/style.css` em um `@media screen and (min-width: 750px)`, remova os efeitos do `:hover` da classe `.projeto-card`

**Comment by humanolaranja** [comment]
Gostaria de fazer este!

**Comment by jessescn** [comment]
Toda sua. qualquer dúvida pode mandar por aqui ou acessar nosso discord :)

**Comment by humanolaranja** [comment]
Aguardando merge, pull request #133
