### ISSUE TITLE
Alterar a lógica da população dos integrantes da seção equipe

### ISSUE THREAD

**Issue by jessescn** [OpenDevUFCG/opendevufcg.org#141]
**Descreva a feature em detalhes**
Atualmente, os dados dos integrantes da seção 'Equipe' estão vindo do arquivo local `docs/home/data/equipe.js`, o ideial seria que essas informações viessem direto do Github.

**Necessidade da feature:**
Obter os dados direto da API do Github permite que os dados permanecam sempre atualizados 

**Como ela pode ser implementada:**
Adicionando uma pasta `services` com um arquivo `.js` que faça a requisição a API do Github e retorne os dados dos membros da organização _opendevufcg_, além de precisar alterar algumas coisas no arquivo `app.js` que estava puxando os dados anteriormente de outro lugar.

**Comment by marcusvlc** [comment]
Gostaria de fazer essa.

**Comment by jessescn** [comment]
Vai que é tua @marcusvlc. Qualquer dúvida, fique a vontade para perguntar por aqui ou pelo nosso discord! 😄
