### ISSUE TITLE
Falta de integrantes no portal

### ISSUE THREAD

**Issue by ivynasantino** [OpenDevUFCG/opendevufcg.org#146]
**Descreva o bug**
Na parte de equipe está faltando integrantes.

**Reprodução do bug**
Entrar no site e ir na parte de equipe. 

Acredito que o erro está [aqui](https://api.github.com/orgs/opendevufcg/public_members)

**Comment by thayannevls** [comment]
As pessoas que estão faltando é por conta que não deixaram público sua participação na organização no github, inclusive não aparece no perfil da pessoa.

Pelo que vi falta @RaylaMedeiros certo? No perfil dela não aparece também https://github.com/RaylaMedeiros

Então não é um problema de implementação e/ou da api, vou fechar a issue :D mas fica um alerta pros membros deixarem público
