### ISSUE TITLE
Mudanças no design do site

### ISSUE THREAD

**Issue by jessescn** [OpenDevUFCG/opendevufcg.org#147]
### Contexto
Estávamos discutindo no discord acerca de mudanças que poderiamos fazer no site a fim de tornar ele mais "vivo" e menos parecido com um pdf gigante. Para facilitar e controlar as ideias e discussões, optamos por trazer a discussão para cá.

### Ideias
Algumas ideias que surgiram no discord foram:

- Cores de seções com gradient
- [Uma porta se abrindo](https://codepen.io/soulbender/pen/KIjHv)
- [Zoom inicial](https://hericlesme.github.io/zoom/)
- [Ideia para mostrar todos os projetos da opendev](https://codepen.io/ksenia-k/pen/pxjZqB)
- [Ideia do haja luz](https://codepen.io/lucasmedina/pen/yOpBXo)
- [Figma com esboço do design](https://www.figma.com/proto/EmR1M56ZqG30A5Uw8agw2U/Portal-OpenDevUFCG?node-id=1%3A2&scaling=min-zoom)

obs: agradecimento huandrey por ter organizado, valeus

Fiquem livre para sugerirem ideias, designs, animações que possam melhorar o site

**Comment by juliohsu** [comment]
Olá, eu gostaria de ajudar nesse design.

**Comment by juliohsu** [comment]
Primeiro como vocês querem algo vivo e alegre então eu criei um personagem que pode ser qualquer membro do grupo, além disso, a porta representa muito bem o nome do grupo OpenDev e da uma boa vinda para o visitante deixando uma impressão de liberdade. Resumindo dps de abrir a porta, aparece “bem vindo” e entra no quarto aparecendo a personagem para fazer introdução e oferecer os tópicos que vocês querem apresentar! (*A porta do início também pode ser decorada dependendo do período do ano, nesse caso eu fiz a do natal)

**Comment by juliohsu** [comment]
Aqui tenho uma página de redirecionamento com um estilo de hacker mexendo terminal para outros sites como tamburetei, glossario, etc...
![image](https://user-images.githubusercontent.com/62186886/80266166-ebdfe700-8670-11ea-85e5-db7928fa9b85.jpg)

![image](https://user-images.githubusercontent.com/62186886/80266183-01eda780-8671-11ea-8207-1c6fc7074eaa.jpg)

**Comment by thayannevls** [comment]
@juliohsu adorei a ideia da porta decorativa com a época do ano! muito legal mesmo. Do personagem tbm gostei, poderia ser algo minimalista tipo assim
![undraw_developer_activity_bv83](https://user-images.githubusercontent.com/6867958/80436415-7163d100-88d5-11ea-94ec-c44af75ae799.png)

**Comment by thayannevls** [comment]
Algumas inspirações https://dev.to/davidepacilio/40-free-html-landing-page-templates-3gfp
