### ISSUE TITLE
Brainstorming: Adição de novas páginas e elementos ao site.

### ISSUE THREAD

**Issue by RodrigoEC** [OpenDevUFCG/opendevufcg.org#161]
**Descreva a feature em detalhes:**
Durante a reunião do core team sobre o site do portal no dia 09/03/2021 foi decidido que serão adicionados novos conteúdos ao site, transformando-o em um hub da OpenDev. Essa adição tem como objetivo centralizar todos os conteúdos criados e disponibilizados pela OpenDevUFCG e, dessa forma, facilitar a transição de um usuário entre os diversos projetos que a organização possui. Todavia, ainda não foi acordado exatamente o que deve ser adicionado ao site para que esse objetivo seja atingido, e é para isso que essa issue existe.

A issue tem como objetivo discutir esses novos elementos que serão adicionados ao site, como páginas ou seções novas, para que em reuniões futuras possamos definir propriamente quais os elementos que serão adicionados.

**Necessidade da feature:**
Para que o site se torne um hub da organização, são necessários novos elementos, como páginas de eventos, blog e projetos. Para concretizar esses elementos são necessárias novas ideias de elementos que podem ser adicionados ao site e também especificar mais detalhadamento os elementos citados previamente. 

**Como ela pode ser implementada:**
Deixe nos comentários sua ideia de algo que poderia ser adicionado ao portal, detalhando e explicando a ideia e o motivo da sua sugestão.

**Comment by RodrigoEC** [comment]
Adicionar uma página de eventos. Com o andromedev, o hacktoberfest e outros eventos vindo aí eu acho que é importante que o site do portal tenha uma página de eventos que sejam realmente um portal para esses outros sites, como o do hacktoberfest ou do andromedev.

Podiamos fazer uma estrutura de cards com cada evento.

**Comment by RodrigoEC** [comment]
Adicionar uma página de projetos. Acredito que pela quantidade de projetos que a OpenDev tem hoje em dia, uma página destinada a expor esses projetos seria muito interessante.

Existem projetos que possuem site e github, sendo assim precisamos pensar em uma forma legal de expor os dois, talvez fazer uma página para cada projeto (Ou um pop-up, não lembro o nome certo), aí dentro dessa estrutura mostrar as informações relevantes do projeto.

**Comment by RodrigoEC** [comment]
O site do Elas possui um "mural de avisos" para expor palestras, eventos e tudo mais que o elas propõe. Acho que seria legal a gente fazer algo parecido para a opendev, para os minicursos, palestras e eventos futuros

**Comment by RodrigoEC** [comment]
Adicionar botão de contribuição (algo que já tem no design que Huandrey fez)

**Comment by JoseRenan** [comment]
Acho que o botão de contribuição poderia ter uma página mostrando várias formas de contribuir, tipo, falando pra abrir o repositório, ler readme e contributing e tal, falar tbm se tiver algum tipo de issue que vc ganhe brinde e como fazer pra ganhar e tbm a questão de doação
