### ISSUE TITLE
Implementação de componente "Sobre nós"

### ISSUE THREAD

**Issue by RodrigoEC** [OpenDevUFCG/opendevufcg.org#169]
**Descreva a feature em detalhes**
[Link para design](https://www.figma.com/file/dwPXm8YbqnDagxVcDaqS7O/OpenDevUFCG-site?node-id=0%3A1)

Implementação do componente a seguir:
![image](https://user-images.githubusercontent.com/42751604/187703659-77732f64-c57b-448f-9fda-025facdb9896.png)

**Necessidade da feature:**

Atenção para a implementação do componente de forma responsiva. Uma boa forma de fazer isso é colocar as seções **Comunidade**, **OpenSource** e **Empoderamento** uma abaixo da outra para telas mobile.

⚠️ Fazer o desenvolvimento a partir da branch `develop`

**Comment by emanamoura** [comment]
Oi ! Gostaria de fazer essa task

**Comment by RodrigoEC** [comment]
Oii @emanamoura tudo certinho! A gente geralmente dá 2 semanas de meio que "deadline" pra as issues e tals, pra meio que manter um ritmo, não significa que vc precise terminar **exatamente** em duas semanas, mas depois desse tempo a gente conversa direitinho pra ver se ta tendo algum impeditivo ta certo?

Qualquer dúvida tu pode conversar comigo la no discord que a gente resolve, obgg por se oferecer pra ajudar! ❤️

**Comment by RodrigoEC** [comment]
Ah, outra coisinha, lembra de ler o CONTRIBUTING.md pra saber como organizar coisas de PR e tals. E também lembrar de iniciar a branch do teu fork a partir da branch development 😄
