### ISSUE TITLE
Implementação de componentes de Util

### ISSUE THREAD

**Issue by RodrigoEC** [OpenDevUFCG/opendevufcg.org#170]
#### ⚠️ Começar desenvolvimento a partir da branch `develop`

**Descreva a feature em detalhes**
[Link do design](https://www.figma.com/file/dwPXm8YbqnDagxVcDaqS7O/OpenDevUFCG-site?node-id=11%3A349)
Componentes Util são componentes que vão ser utilizados em outros componentes. Os componentes util são:

- **Membro/ex-membro**: Componente que vai receber o nome do membro, o src da imagem que vai ser exibida e o link para o github da pessoa. Uma boa também é adicionar um tooltip com o nome que é recebido como prop.
Ex.:
![image](https://user-images.githubusercontent.com/42751604/187709045-4f19eb62-f1a7-45b9-872a-48a99449dd77.png)

- **Título de seção**: Componente de título que vai ser usado em seções em todo o site
Ex.:
![image](https://user-images.githubusercontent.com/42751604/187709684-ef9cde44-0630-47cd-993e-dc9439ea0c20.png)

⚠️ Fazer o desenvolvimento a partir da branch `development`

**Comment by emanamoura** [comment]
Hello de novo, gostaria de fazer essa task !

**Comment by RodrigoEC** [comment]
Oii de novo @emanamoura kkkkkkk pode pegarr, ja sabes o procedimento 😄 Lembrando de começar da `develop` kkkkkkkkkkk
