### ISSUE TITLE
Implementação do componente Header

### ISSUE THREAD

**Issue by RodrigoEC** [OpenDevUFCG/opendevufcg.org#172]
#### ⚠️ Começar desenvolvimento a partir da branch `develop`

**Descreva a feature em detalhes**

[Link do design no figma](https://www.figma.com/file/dwPXm8YbqnDagxVcDaqS7O/OpenDevUFCG-site?node-id=11%3A349)
Implementação do componente Header. A ideia é que a página que o usuário está atualmente fique com um sublinhado abaixo da palavra correspondente
![image](https://user-images.githubusercontent.com/42751604/187712137-2bbffa57-6146-472b-9f70-c01150c608b2.png)

⚠️ Fazer o desenvolvimento a partir da branch `develop`, essa é a branch que estamos usando para fazer o redesign do projeto. ❤️

**Comment by LeandraOS** [comment]
Queroooo

**Comment by RodrigoEC** [comment]
ALocadahh, tu ja sabe o procedimento ❤️ Lembra de começar o desenvolvimento da `develop`
