### ISSUE TITLE
Implementação de componente BlogPost

### ISSUE THREAD

**Issue by RodrigoEC** [OpenDevUFCG/opendevufcg.org#173]
#### ⚠️ Começar desenvolvimento a partir da branch `develop`

**Descreva a feature em detalhes**
[Link do design no figma](https://www.figma.com/file/dwPXm8YbqnDagxVcDaqS7O/OpenDevUFCG-site?node-id=0%3A1)
Implementação do componente que representa um post da OpenDev no nosso blog

![image](https://user-images.githubusercontent.com/42751604/187918090-ed20a9a2-e918-4ca1-ae63-3d0fb4239802.png)

A ideia do componente é que ele receba todas essas infos evidentes na imagem, mas também um link que quando o usuário clicar no post ele seja redirecionado para o link que é passado como prop do componente.

warning OBS: Fazer sua branch a partir da development, esta é a branch que estamos usando pra iniciar redesign.

**Como ela pode ser implementada:**
O componente deve receber como prop um objeto no seguinte formato:

```javaScript
const payload = {
  title: string,
  url: string,
  reading_time_minutes: integer,
  published_at: string (no formato "2021-07-12T17:02:58Z"),
  author: string,
}
```

É importante que a implementação receba esse formato de prop pelo fato de esse ser o formato de objeto que a API do DEV.to retorna os dados.

**Comment by tarsojabbes** [comment]
Oi, posso ajudar nessa implementação!

**Comment by RodrigoEC** [comment]
Oii amg,  vou te dar assignn, obg pelo interesse em contribuirr 😄 .

A gente geralmente dá uma "deadline" de 2 semanas pra a implementação da issue, tu não precisa necessariamente fazer isso em duas semanas, mas depois desse tempo caso tu não tenha terminado eu falo contigo pra ver se teve algum impedimento e tals, ta bem?

Ah, outra coisinha, lembra de começar o desenvolvimento no teu fork a partir da branch **develop**, ta certo? Essa é a branch que a gente ta usando pra fazer o redesign do portal ❤️ .

Qualquer dúvida ou impedimento pode falar comigo (ou qualquer pessoa com o badget de core) no discord! Obrigaduuu novamente
