### ISSUE TITLE
Implementação de componente de redes sociais

### ISSUE THREAD

**Issue by RodrigoEC** [OpenDevUFCG/opendevufcg.org#174]
**Descreva a feature em detalhes**
[Link do design do projeto no figma](https://www.figma.com/file/dwPXm8YbqnDagxVcDaqS7O/OpenDevUFCG-site)

A ideia é implementar um componente mais geral que servirá tanto para o github como para o discord da opendev
![image](https://user-images.githubusercontent.com/42751604/187922693-1f5ccabd-b309-493c-a7ab-5b8c9caa6f6d.png)

⚠️ OBS: Fazer sua branch a partir da `development`, esta é a branch que estamos usando pra iniciar redesign.

**Sugestão de implementação:**
Uma boa ideia seria passar o título, texto e ícone como uma prop e fazer um componente genérico que recebe essas informações

⚠️ Lembre-se de que esse componente vai ser visualizado em telas mobile, ou seja, é preciso se preocupar com a responsividade. Se o componente ficar ok em telas menores na primeira implementação tudo certo, mas lembre-se de checar isso ❤️

**Comment by jpalvesl** [comment]
Oie, eu tenho interesse na issue.

**Comment by RodrigoEC** [comment]
Oii, vou te dar assignn, obg pelo interesse em contribuirr 😄.

A gente geralmente dá uma "deadline" de 2 semanas pra a implementação da issue, tu não precisa **necessariamente** fazer isso em duas semanas, mas depois desse tempo caso tu não tenha terminado eu falo contigo pra ver se teve algum impedimento e tals, ta bem? 

Ah, outra coisinha, lembra de começar o desenvolvimento no teu fork a partir da branch development, ta certo? Essa é a branch que a gente ta usando pra fazer o redesign do portal ❤️.

Qualquer dúvida ou impedimento pode falar comigo (ou qualquer pessoa com o badget de core) no discord! Obrigaduuu novamente
