### ISSUE TITLE
Implementação do componente de Timeline

### ISSUE THREAD

**Issue by RodrigoEC** [OpenDevUFCG/opendevufcg.org#176]
**Descreva a feature em detalhes**
[Link do design no figma](https://www.figma.com/file/dwPXm8YbqnDagxVcDaqS7O/OpenDevUFCG-site?node-id=2%3A2)

Implementação do componente Timeline dos nossos eventos. A ideia é que quando o usuário passar o mouse por cima da imagem que representa o evento o apareça com as informações do evento.
![image](https://user-images.githubusercontent.com/42751604/187941910-8798d70c-2f66-4134-a38b-fee4d11d9ba5.png)

⚠️ OBS: Fazer a implementação a partir da branch `development`, essa é a branch que estamos usando para a implementação do redesign.

**Comment by RodrigoEC** [comment]
@JuanBarros2 comenta aqui pra eu te dar assign nessa issue, pf

**Comment by JuanBarros2** [comment]
Eu ia pegar essa mas vai ficar muito grande se colocar em um PR só. Acho melhor quebrar em mini issues, tipo: Criar elemento base, criar elemento de hover, criar esqueleto de timeline... Tu acha que fica melhor ou muito complicado?

**Comment by RodrigoEC** [comment]
Verdade @JuanBarros2! Vou criar algumas issues menores. Tu ja fez alguma coisa da issue ou posso dividir do jeito que eu penso?

**Comment by JuanBarros2** [comment]
Pode dividir 😄

**Comment by RodrigoEC** [comment]
Pronto @JuanBarros2 criei mais duas issues viu, vê la pra ver se tu quer desenvolver alguma
