### ISSUE TITLE
Colocar sombra nos cards de Projetos

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/opendevufcg.org#49]
Na sessão de Projetos, os cards estão sem sombra por conta do fundo, seria bom implementar uma sombra minuciosa.

**Comment by lucasaarcoverde** [comment]
Oi, abri o site e vi que na sessão de projetos os cards já estão com sombra.
<img width="640" alt="Screen Shot 2019-09-04 at 14 14 34" src="https://user-images.githubusercontent.com/20579226/64276527-90fd5200-cf1e-11e9-93a1-9d62649d3f5b.png">
É preciso clarear a cor do fundo ou escurecer a sombra? :)

**Comment by thayannevls** [comment]
Oie @lucasaarcoverde , hmm esqueci de atualizar que a sombra no **hover** foi implementada na #85 

Seria legal uma sobra com o card normal, e intensificar quando dá o hover, tipo assim [assim](https://codepen.io/BastianAndre/pen/PzwEYe)

tu tem interesse de fzr essa issue?

**Comment by lucasaarcoverde** [comment]
Tenho simm, posso fazer?

**Comment by thayannevls** [comment]
claroo, mto obg :heart: 

E também, se tu achar que fique melhor de outro jeito ou que precise ter outra coisa, fica a vontade pra sugerir :)

**Comment by lucasaarcoverde** [comment]
Massa!! :)

**Comment by thayannevls** [comment]
Feito em #89
