### ISSUE TITLE
Adicionar descrição em Equipe

### ISSUE THREAD

**Issue by juliobguedes** [OpenDevUFCG/opendevufcg.org#51]
Somos um grupo open source, e não faria muito sentido manter uma seção de equipe, afinal, equipe são todos os contribuidores. Dessa forma, creio fazer sentido adicionar uma breve descrição explicando o motivo daquelas pessoas estarem ali (o core)

**Comment by ThiagoWhispher** [comment]
Em #137 foi adicionado uma frase sugerida por @jessescn englobando todos da equipe, se fosse fazer algo explicando o motivo de cada um seria legal dar um highlight quando o usuário clicasse em uma das pessoas abrindo uma descrição pessoal (em vez do link do github, talvez esse link pode ser passado na descrição pessoal). Algo como "Comecei a me interessar por projeto x e quando me vi estava apaixonado pela sua ideia e tecnologias, hoje sou um dos cores dessa equipe buscando sempre auxiliar no que for necessário"

**Comment by juliobguedes** [comment]
Oi @ThiagoWhispher , acho que faz mais sentido abrir uma nova issue, já que teu comentário se refere a uma nova feature. Esta issue deveria ter sido fechada quando a #137 foi aberta, por estar duplicada.

**Comment by thayannevls** [comment]
Vou abrir uma nova @ThiagoWhispher @juliobguedes
