### ISSUE TITLE
Criar um rodapé para o site

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/opendevufcg.org#65]
**Descrição da melhoria:**
Criar um rodapé no fim da página que contenha as redes sociais e outras informações que julgarem necessárias;

**Necessidade da melhoria:**
Para dispor informações importantes, como redes sociais, de maneira resumida e fácil.

**Como ela pode ser implementada:**
É preciso criar um componente do rodapé e depois implementar para que ele apareça em todas as rotas da aplicação, sempre sendo o último da página.

Talvez a solução envolva o [Routing](https://nuxtjs.org/guide/routing).

**Imagens:**
Exemplos
![image](https://user-images.githubusercontent.com/6867958/55572168-6728d080-56dd-11e9-8a1f-734ea07aff9b.png)

**Comment by LukeHxH** [comment]
Vou trabalhar nisso esse fdp :p
