### ISSUE TITLE
Cards de projetos não estão se comportando bem

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/opendevufcg.org#74]
**Descreva o bug**
Cards não estão responsivos em algumas telas, tanto em menores quanto grandes.

**Reprodução do bug**
Passos para reproduzir o comportamento indesejado:

1. No seu browser visite o site, e no chrome dev tools mude o dispositivo
2. Teste a responsividade mudando o tamanho da tela

**Comportamento desejado**
Que os cards não diminuíssem tanto seus tamanhos em telas menores, deixando o texto agradável de ler. E que a listagem pudesse se quebrar de maneira apropriada dependendo do tamanho da tela

**Capturas de tela**
![62305000-759db380-b455-11e9-9cec-f9c6b85a0ca3](https://user-images.githubusercontent.com/6867958/62338799-2c2e8200-b4b0-11e9-9edb-9e0c97fb921b.png)
<img width="1680" alt="Screen Shot 2019-08-01 at 22 55 49" src="https://user-images.githubusercontent.com/6867958/62338800-2c2e8200-b4b0-11e9-94ed-9059163be771.png">
<img width="1680" alt="Screen Shot 2019-08-01 at 22 55 43" src="https://user-images.githubusercontent.com/6867958/62338801-2c2e8200-b4b0-11e9-9d01-b3700d0dea3d.png">

**Contexto adicional**
Apenas com propriedades de [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) podemos resolver isso.

**Comment by RaylaMedeiros** [comment]
Além do que, acredito que todos os cards deveriam estar com a mesma largura

**Comment by thayannevls** [comment]
faz ai @RaylaMedeiros 😃

**Comment by thayannevls** [comment]
Resolvido em #73
