### ISSUE TITLE
Nova tela inicial para o site

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/opendevufcg.org#77]
**Descrição da melhoria:**
Queremos mudar a tela inicial, aceitamos novas ideias e sugestões. Elas devem conter a nova logo!

**Imagens:**
Nova logo:
![3547f022-e218-4bd1-a8f7-38341c3ebbe6](https://user-images.githubusercontent.com/6867958/62493358-46fe4080-b7a7-11e9-8393-9e3c6ea269fc.jpeg)

**Comment by thayannevls** [comment]
@RaylaMedeiros

**Comment by thayannevls** [comment]
[Aqui](https://drive.google.com/drive/folders/1nxfXGuJM-v7ZSAqvQwWI1dAMNCXVzwCE?usp=sharing) está a logo e o favicon

@RaylaMedeiros @jessescn vcs tem sugestões de cm a gnt poderia fzr com a primeira seção usando a nova logo?

**Comment by jessescn** [comment]
@thayannevls Posso pegar a parte de adicionar a logo para ir adiantando o processo

**Comment by thayannevls** [comment]
Toop @jessescn toda sua
