### ISSUE TITLE
Textos da sessão 'Sobre nós' não estão centralizados

### ISSUE THREAD

**Issue by jessescn** [OpenDevUFCG/opendevufcg.org#78]
**Descreva o bug**
A listas no site estão com uma padding-left, que os estão descentralizando

**Comportamento desejado**
Deve ser removido essa margin a fim de centralizar a lista horizontalmente a lista com a página

**Capturas de tela**

![Captura de tela de 2019-08-20 21-13-33](https://user-images.githubusercontent.com/33502846/63393096-eb7ba780-c38f-11e9-9d31-5b3b8fff793f.png)
i

**Comment by thayannevls** [comment]
@jessescn Só não consigo visualizar onde que foi inserido esse padding-left

**Comment by jessescn** [comment]
pelo que eu tava vendo, esse padding é da tag ul mesmo, como não resetaram os valores da padding nem do margin no começo, acabou que estruturaram os elementos do site em cima desses estilos. Creio que talvez alguns outros lugares precisem ser corrigidos caso forem resetar o padding/margin do html todo (talvez seja o mais correto, ou apenas fui doutrinado por Dalton).

**Comment by thayannevls** [comment]
Verdade, nas listagens de projetos e equipe tbm usei *ul* e *li* pelo que lembre. Tu iria querer tentar fazer isso?

**Comment by jessescn** [comment]
Posso fazer sim

**Comment by jessescn** [comment]
@thayannevls eu tava corrigindo o padding e tals e me deparei com isso que já estava 

![Captura de tela de 2019-08-25 11-13-33](https://user-images.githubusercontent.com/33502846/63651276-6c88c500-c729-11e9-83eb-e07d196b23c0.png)

Talvez isso seja um pouco desconfortável pra ler caso o usuário esteja em um dispositivo mobile, então eu alterei um pouco e ficou assim

![Captura de tela de 2019-08-25 11-10-59](https://user-images.githubusercontent.com/33502846/63651296-92ae6500-c729-11e9-8282-608a7e21cd95.png)

O que tu achas?

**Comment by thayannevls** [comment]
@jessescn Ficou perfeito! Realmente tava bem desconfortável, por mim já está ótimo 😄
