### ISSUE TITLE
Melhorar efeito de hover dos cards

### ISSUE THREAD

**Issue by jessescn** [OpenDevUFCG/opendevufcg.org#84]
**Descrição da melhoria:**
Melhorar o efeito de hover dos cards da comunidade e dos projetos

**Necessidade da melhoria:**
Melhorar visualmente o site

**Como ela pode ser implementada:**
Alterar o atributo transform do hover dos cards, além de adicionar um transition para deixar o efeito mais suave

**Comment by jessescn** [comment]
@thayannevls algo tipo isso?

![OpenDevUFCG](https://user-images.githubusercontent.com/33502846/63897854-fc01d280-c9cc-11e9-8903-1e877c7df6d5.gif)

**Comment by thayannevls** [comment]
@jessescn Era issooo mesmo. Quando tu passa nos cards debaixo fica como?

**Comment by jessescn** [comment]
nesse caso eu coloquei só pra empurrar pra os lados, mas pra baixo também seria uma opção

**Comment by thayannevls** [comment]
Acho que tá de boas assim ficou top.

No novo design a gente pode dar uma reestruturada nessa seção também. Abre PR ❤️
