### ISSUE TITLE
Modificar seção de equipe para ser círculos

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/opendevufcg.org#88]
**Descrição da melhoria:**
Modificar seção de equipe para ser círculos invés de hexágonos.

**Necessidade da melhoria:**
Hexágonos não fazem mais parte da nossa logo.

**Como ela pode ser implementada:**
Provavelmente tirando a prop `clip-path` e colocando um `border-radius`

**Contexto adicional:**
Em breve vai ter mais informações sobre nosso core team nessa seção

**Comment by jessescn** [comment]
Tipo isso?

![Captura de tela de 2019-09-05 13-15-43](https://user-images.githubusercontent.com/33502846/64359726-51e30580-cfdf-11e9-911e-d1466b1b1785.png)

**Comment by thayannevls** [comment]
que rápido kkkkkk

siiiim, seria tipo isso msm. Tu testou se fica legal com borda?

**Comment by jessescn** [comment]
![Captura de tela de 2019-09-05 14-26-40](https://user-images.githubusercontent.com/33502846/64364430-3846bb80-cfe9-11e9-9288-444bd1d016b5.png)
 Talvez com uma cor diferente, mas eu prefiro sem. O que tu acha?

**Comment by thayannevls** [comment]
fica melhor sem mesmo :/ só sugeri por causa de fotos com fundo branco mas n deu mto certo kkkk

se quiser submeter :)
