### ISSUE TITLE
Adicionar logo nova

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/opendevufcg.org#90]
**Descrição da melhoria:**
Seria interessante ter a novo logo da organização

**Necessidade da melhoria:**
Pode ser que novatos não entendam que somos a mesma organização visto que o design
está diferente.

**Como ela pode ser implementada:**
Trocando o arquivo da logo antigo pela nova

**Comment by thayannevls** [comment]
Referente a #77

**Comment by thayannevls** [comment]
Falta eu disponibilizar o arquivo

**Comment by thayannevls** [comment]
Adicionei lá e coloquei o link do arquivo. vou fechar essa pra n ficar duplicado
