### ISSUE TITLE
Guia interativo de contribuição para iniciante em contribuição

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/opendevufcg.org#91]
**Descrição da melhoria:**
Tava pensando em criar algum componente que ajudasse os MUITO iniciantes
a contribuírem. Colocar uma especie de step-by-step que ajudasse a filtrar os 
projetos que mais se encaixasse com o perfil dele.

**Necessidade da melhoria:**
Para um iniciante contribuir ele terá que conhecer cada um dos projetos e pode
ser que não estimule muito o iniciante a ir ler a descrição e as tecnologias de
cada projeto.

**Como ela pode ser implementada:**
Pensei em criar um especie de teste que o usuário entra com características dele
que ajude a filtrar o melhor projeto para ele. Por exemplo: eu sei programar web,
gosto de front end, tenho facilidade com vue; resultado: Portal. Estou avançado
no curso, não gosto de web, sei markdown; resultado: Tamburetei.

**Contexto adicional:**
Também seria possível extrair métricas do perfil das pessoas que se engajam
nos nossos projetos para tentar facilitar a contribuição.

**Comment by thayannevls** [comment]
Juan isso n é mais parecido com o issueao?

**Comment by JuanBarros2** [comment]
Eu tava pensando num escopo mais simples que o issueai (meio buzzfead kkkkk). Além de que seria focado só nos projetos do OpenDevUFCG. Poderia ser 2 ou 3 passos só.

**Comment by ThiagoWhispher** [comment]
No caso seria algum tipo de filtro que ajudasse a indicar projetos que se encaixassem no perfil do possível contribuidor? Isso seria talvez interessante no projeto de Issueai

**Comment by JuanBarros2** [comment]
Sim @ThiagoWhispher . Acabei conversando depois lá no discord e ficou acertado deixar essa responsabilidade pra o IssueAi mesmo. Pode fechar a issue @thayannevls ?

**Comment by thayannevls** [comment]
Posso fechar, vamos depois discutir isso numa reunião do issueai
