### ISSUE TITLE
Adicionar seção sobre o blog

### ISSUE THREAD

**Issue by JRobsonJr** [OpenDevUFCG/opendevufcg.org#99]
**Descrição da melhoria:**
Seria interessante ter uma divulgação do [blog do OpenDevUFCG](https://github.com/OpenDevUFCG/OpenDevUFCGBlog) na tela inicial do portal.

**Necessidade da melhoria:**
É importante divulgar todos os nossos projetos :stuck_out_tongue_winking_eye: 

**Como ela pode ser implementada:**
Pode ser inserida uma seção no site, talvez após a parte de "Nossos projetos". O ideal seria ter cards para as publicações, mostrando ao menos o título, autor e algumas tags.

**Comment by thayannevls** [comment]
@JRobsonJr Podiamos incluir como card, e depois adicionar numa seção vários links para nossas mídias:

1. instagram
2. twitter
3. blog

O que acha?

**Comment by JRobsonJr** [comment]
Gostei muito da ideia, @thayannevls!
